server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:classroomy-server
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

domelian:
  app:
    jwtCookieName: domelian
    jwtSecret: dOmelianSecretKey
    jwtExpirationMs: 86400000